// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SNSW_API.Data;

namespace SNSW_API.Data.Migrations
{
    [DbContext(typeof(SNSWContext))]
    [Migration("20210506082034_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SNSW_API.Models.Insurer", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Code");

                    b.Property<string>("RegistrationPlate_number");

                    b.HasKey("Name");

                    b.HasIndex("RegistrationPlate_number");

                    b.ToTable("Insurers");
                });

            modelBuilder.Entity("SNSW_API.Models.Registration", b =>
                {
                    b.Property<string>("Plate_number")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Plate_number");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("SNSW_API.Models.RegistrationDetail", b =>
                {
                    b.Property<DateTime>("Expiry_date");

                    b.Property<bool>("Expired");

                    b.Property<string>("RegistrationPlate_number");

                    b.HasKey("Expiry_date");

                    b.HasIndex("RegistrationPlate_number");

                    b.ToTable("RegistrationDetails");
                });

            modelBuilder.Entity("SNSW_API.Models.Vehicle", b =>
                {
                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<int?>("Gross_mass");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<string>("RegistrationPlate_number");

                    b.Property<int?>("Tare_weight");

                    b.Property<string>("Vin");

                    b.HasKey("Type");

                    b.HasIndex("RegistrationPlate_number");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SNSW_API.Models.Insurer", b =>
                {
                    b.HasOne("SNSW_API.Models.Registration")
                        .WithMany("Insurers")
                        .HasForeignKey("RegistrationPlate_number");
                });

            modelBuilder.Entity("SNSW_API.Models.RegistrationDetail", b =>
                {
                    b.HasOne("SNSW_API.Models.Registration")
                        .WithMany("RegistrationDetails")
                        .HasForeignKey("RegistrationPlate_number");
                });

            modelBuilder.Entity("SNSW_API.Models.Vehicle", b =>
                {
                    b.HasOne("SNSW_API.Models.Registration")
                        .WithMany("Vehicles")
                        .HasForeignKey("RegistrationPlate_number");
                });
#pragma warning restore 612, 618
        }
    }
}
